# -*- coding: utf-8 -*-
"""23101137_Imtiaz Hossain_CSE422_30_Assignment03_Summer2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlJVH97-aQeirrX4XH6XtNcPxJe53gB0

# Task 1
"""

#--> Task 1

input = open('/content/drive/MyDrive/BRACU 8th Semester/CSE422_LAB/LAB - 3/Input Files/task_1.txt','r')
output = open('/content/drive/MyDrive/BRACU 8th Semester/CSE422_LAB/LAB - 3/Output Files/task_1.txt','w')

initial_nucleotides_pool = input.readline().rstrip("\n").split(',')
target = input.readline().rstrip("\n")
temp = input.readline().rstrip("\n").split()

my_student_ID_list = []

for i in range(len(temp)):
    my_student_ID_list.append(int(temp[i]))

def utility(gene, target, weights):
    max_length = max(len(gene), len(target))
    total = 0

    for i in range(max_length):
        ascii_gene= 0
        ascii_target = 0

        if i < len(gene):
            ascii_gene = ord(gene[i])

        if i < len(target):
            ascii_target = ord(target[i])

        if i < len(weights):
            w = weights[i]

        else:
            w = 1

        total += w * abs(ascii_gene - ascii_target)

    return -total

def minimax(seq, pool, alpha, beta):
    if len(pool) == 0:
        u = utility(seq, target, weights)
        return u, seq

    if len(seq) % 2 == 0:
        best_val = float('-inf')
        best_seq = None

        for i in range(len(pool)):
            nuc = pool[i]
            new_seq = seq + nuc
            new_pool = pool[:i] + pool[i+1:]
            val, full_seq = minimax(new_seq, new_pool, alpha, beta)

            if val > best_val:
                best_val = val
                best_seq = full_seq

            if val > alpha:
                alpha = val

            if alpha >= beta:
                break

        return best_val, best_seq

    else:
        best_val = float('inf')
        best_seq = None

        for i in range(len(pool)):
            nuc = pool[i]
            new_seq = seq + nuc
            new_pool = pool[:i] + pool[i+1:]
            val, full_seq = minimax(new_seq, new_pool, alpha, beta)

            if val < best_val:
                best_val = val
                best_seq = full_seq

            beta = min(val, beta)

            if best_val <= alpha:
                break

        return best_val, best_seq


if len(target) > len(my_student_ID_list):
    output.write("Invalid\n")
    input.close()
    output.close()

else:
    weights = my_student_ID_list[-len(target):]
    util, gene_sequence = minimax("", initial_nucleotides_pool, float('-inf'), float('inf'))

    output.write(f"Best gene sequence generated: {gene_sequence}" + "\n")
    output.write(f"Utility score: {str(util)}")

input.close()
output.close()

"""# Task 2

"""

#--> Task 2

input = open('/content/drive/MyDrive/BRACU 8th Semester/CSE422_LAB/LAB - 3/Input Files/task_2.txt','r')
output = open('/content/drive/MyDrive/BRACU 8th Semester/CSE422_LAB/LAB - 3/Output Files/task_2.txt','w')

initial_nucleotides_pool = input.readline().rstrip("\n").split(',')
target = input.readline().rstrip("\n")
temp = input.readline().rstrip("\n").split()

my_student_ID_list = []

for i in range(len(temp)):
    my_student_ID_list.append(int(temp[i]))

def utility(gene, target, weights):
    max_length = max(len(gene), len(target))
    total = 0

    for i in range(max_length):
        ascii_gene = 0
        ascii_target = 0

        if i < len(gene):
            ascii_gene = ord(gene[i])

        if i < len(target):
            ascii_target = ord(target[i])

        if i < len(weights):
            w = weights[i]

        else:
            w = 1

        total += w * abs(ascii_gene - ascii_target)

    return -total

def booster_utility(gene, target, weights):
    max_length = max(len(gene), len(target))
    total = 0

    s_position = -1

    for i in range(len(gene)):
        if gene[i] == 'S':
            s_position = i
            break

    first_two_digits = int(str(my_student_ID_list[0]) + str(my_student_ID_list[1]))
    booster_multiplier = first_two_digits / 100.0

    for i in range(max_length):
        ascii_gene = 0
        ascii_target = 0

        if i < len(gene):
            ascii_gene = ord(gene[i])

        if i < len(target):
            ascii_target = ord(target[i])

        if i < len(weights):
            w = weights[i]

            if s_position != -1 and i >= s_position:
                w *= booster_multiplier
        else:
            w = 1

        total += w * abs(ascii_gene - ascii_target)

    return -total

def minimax_normal(seq, pool, alpha, beta):
    if len(pool) == 0:
        return utility(seq, target, weights), seq

    if (len(seq) % 2 == 0):
        best_val = float('-inf')
        best_seq = None

        for i in range(len(pool)):
            nuc = pool[i]
            new_seq = seq + nuc
            new_pool = pool[:i] + pool[i+1:]
            val, full_seq = minimax_normal(new_seq, new_pool, alpha, beta)

            if val > best_val:
                best_val = val
                best_seq = full_seq

            alpha = max(alpha, val)

            if beta <= alpha:
                break

        return best_val, best_seq

    else:
        best_val = float('inf')
        best_seq = None

        for i in range(len(pool)):
            nuc = pool[i]
            new_seq = seq + nuc
            new_pool = pool[:i] + pool[i+1:]
            val, full_seq = minimax_normal(new_seq, new_pool, alpha, beta)

            if val < best_val:
                best_val = val
                best_seq = full_seq

            beta = min(beta, val)

            if beta <= alpha:
                break

        return best_val, best_seq

def minimax_special(seq, pool, alpha, beta):
    if len(pool) == 0:
        return booster_utility(seq, target, weights), seq

    if (len(seq) % 2 == 0):
        best_val = float('-inf')
        best_seq = None

        for i in range(len(pool)):
            nuc = pool[i]
            new_seq = seq + nuc
            new_pool = pool[:i] + pool[i+1:]
            val, full_seq = minimax_special(new_seq, new_pool, alpha, beta)

            if val > best_val:
                best_val = val
                best_seq = full_seq

            alpha = max(alpha, val)

            if beta <= alpha:
                break

        return best_val, best_seq

    else:
        best_val = float('inf')
        best_seq = None

        for i in range(len(pool)):
            nuc = pool[i]
            new_seq = seq + nuc
            new_pool = pool[:i] + pool[i+1:]
            val, full_seq = minimax_special(new_seq, new_pool, alpha, beta)

            if val < best_val:
                best_val = val
                best_seq = full_seq

            beta = min(beta, val)

            if beta <= alpha:
                break

        return best_val, best_seq

if len(target) > len(my_student_ID_list):
    output.write("Invalid")

else:
    weights = my_student_ID_list[-len(target):]

    pool_with_s = initial_nucleotides_pool.copy()

    if 'S' not in pool_with_s:
        pool_with_s.append('S')

    normal_util, normal_gene = minimax_normal("", initial_nucleotides_pool, float('-inf'), float('inf'))
    special_util, special_gene = minimax_special("", pool_with_s, float('-inf'), float('inf'))

    if special_util > normal_util:
        output.write("YES\n")

    else:
        output.write("NO\n")

    output.write("With special nucleotide\n")
    output.write(f"Best gene sequence generated: {special_gene},\n")
    output.write(f"Utility score: {special_util:.2f}")

input.close()
output.close()