# -*- coding: utf-8 -*-
"""23101137_Imtiaz Hossain_CSE422_30_Assignment01_Summer2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_n6C7NGr1paHUImMSww0_-6i6wEr7DF

# *Part 1*
"""

input = open('/content/drive/MyDrive/BRACU 8th Semester/CSE422_LAB/LAB - 1/Input_Files/Part1_input.txt','r')
output = open('/content/drive/MyDrive/BRACU 8th Semester/CSE422_LAB/LAB - 1/Output_Files/Part1_output.txt', 'w')

n, m = input.readline().rstrip("\n").split()
n = int(n)  # height ---> row
m = int(m)  # width  ---> col

# print(n)
# print(m)

a, b= input.readline().rstrip("\n").split()

a= int(a)  # (a, b) index of the entry point of the maze
b= int(b)  # ---^

# print(a)
# print(b)

c, d= input.readline().rstrip("\n").split()

c= int(c)  # (c, d) index of the entry point of the maze
d= int(d)  # ---^

# print(c)
# print(d)

maze = []

for i in range(n):
    temp = input.readline().rstrip("\n") # '###0####'
    temp = list(temp)                    # ['#', '#', '#', '0', '#', '#', '#', '#']
    maze.append(temp)

#print(maze)

entry_point = [a, b]   # (0, 3) --> ['#', '#', '#', '0', '#', '#', '#', '#']
exit_point = [c, d]    # (6, 5) --> ['#', '#', '#', '#', '#', '0', '#', '#']

#print(entry_point)
#print(exit_point)

total_path_cost = 0

import heapq

def maze_solver(maze, entry_point, exit_point):

    if entry_point[0] < n and entry_point[0] > -1 and entry_point[1] < m and entry_point[1] > -1:         # ---> Checking validility of entry_point
        if exit_point[0] < n and exit_point[0] > -1 and exit_point[1] <= m and exit_point[1] > -1:        # ---> Checking validility of exit_point
            if maze[entry_point[0]][entry_point[1]] == '0' and maze[exit_point[0]][exit_point[1]] == "0": # ---> Checking enter_point/exit_point if it is blocked or not
                if entry_point[0] == exit_point[0] and entry_point[1] == exit_point[1]:                   # ---> To check if it's the exit point or not.
                    output.write(str(total_path_cost) + "\n")
                    return

                else:

                    def manhattan_distance(x, y):                    # ---> Manhattan distance (x, y) = |x1 - x2| + |y1- y2|
                        return abs(x[0] - y[0]) + abs(x[1] - y[1])

                    possible_moves = [(-1, 0, "U"), (1, 0, "D"), (0, 1, "R"), (0, -1, "L")]

                    seen_idx = set()
                    priority_queue = []

                    # initital cost = 0

                    heapq.heappush(priority_queue, (manhattan_distance(entry_point, exit_point), 0, tuple(entry_point), ""))   # ---> initital cost, cost_so_far = 0
                                                                                                                               # ---> Manhattan distance = |0 - 6| + |3 - 5| = 8

                    # f = total_estimated_cost -> 4
                    # g = cost_so_far          -> 0
                    # (x, y) = position        -> (0, 3)
                    # path = directions taken  -> ""

                    while priority_queue:
                        f, g, (x, y), path = heapq.heappop(priority_queue)

                        if (x, y) == tuple(exit_point):
                            output.write(str(g) + "\n")
                            output.write(path)
                            return

                        if (x, y) in seen_idx:
                            continue

                        seen_idx.add((x, y))

                        for i, j, k in possible_moves:
                            new_x = x + i
                            new_y = y + j

                            if new_x < n and new_x > -1 and new_y < m and new_y > -1:
                                if maze[new_x][new_y] == "0":
                                    if (new_x, new_y) not in seen_idx:
                                        new_h = manhattan_distance((new_x, new_y), exit_point)
                                        new_g = g + 1

                                        new_f = new_g + new_h # Total

                                        heapq.heappush(priority_queue, (new_f, new_g, (new_x, new_y), path + k))  # Adding next step to the queue


                    output.write("-1")     # ---> print("While No Path Found")
            else:
                output.write("-1")         # ---> print("Entry/Exit Point is Blocked")
        else:
            output.write("-1")             # ---> print("Invalid Exit Point")
    else:
        output.write("-1")                 # ---> print("Invalid Entry Point")



maze_solver(maze, entry_point, exit_point)

input.close()
output.close()

"""# *Part 2*"""

input1 = open("/content/drive/MyDrive/BRACU 8th Semester/CSE422_LAB/LAB - 1/Input_Files/Part2_input.txt","r")
output1 = open("/content/drive/MyDrive/BRACU 8th Semester/CSE422_LAB/LAB - 1/Output_Files/Part2_output.txt","w")

n, m = input1.readline().rstrip("\n").split()
n = int(n)  # number of vertices --> 6
m = int(m)  # number of edges    --> 7

a, b= input1.readline().rstrip("\n").split()

a= int(a)  # initial vertex --> 1
b= int(b)  # goal vertex    --> 6

heuristics = {}
for i in range(n):
    x, y= input1.readline().rstrip("\n").split()
    x= int(x)
    y= int(y)

    heuristics[x] = y

#print(heuristics)

edges = []
for i in range(m):
    source, destnination = input1.readline().rstrip("\n").split()
    source = int(source)
    destnination = int(destnination)

    edges.append([source, destnination])

# print(edges)

############################<---Create Graph-->#################################

def create_graph(edges):
    G = {}

    for u, v in edges:
        if u not in G:
            G[u] = []
        if v not in G:
            G[v] = []

        G[u].append(v)
        G[v].append(u)

    return G

G= create_graph(edges)
#print(G)

#################################<---BFS--->####################################

from collections import deque

def bfs(G, goal):
    Q= deque()
    distance = {}

    for u in G:
        distance[u] = float('inf')

    distance[goal] = 0
    Q.append(goal)

    while Q:
        u = Q.popleft()

        for i in G[u]:
            if distance[i] == float('inf'):
                distance[i] = distance[u] + 1
                Q.append(i)

        #print(u)

    return distance

distance_dict = bfs(G, b)
#print(distance_dict)

################################################################################

inadmissible_nodes = []

for i in distance_dict:
    if heuristics[i] > distance_dict[i]:
        inadmissible_nodes.append(i)

temp= ""
if inadmissible_nodes != []:
    output1.write("0\n")
    for i in range(len(inadmissible_nodes)):
        temp += f"{str(inadmissible_nodes[i])} "

    temp = temp.rstrip()
    # print(temp)
    output1.write(temp)

else:
    output1.write("1")

input1.close()
output1.close()

"""# Test Cases

**Part - 1**
"""

'''
7 8
0 3
6 5
###0####
#000000#
###0#00#
#000#00#
#0######
#000000#
#####0##

Output:
12
DDDLLDDRRRRD

-------------------

10 12
0 1
9 8
#0##########
#000000###0#
###0###0##0#
#0#0#000##0#
#0#0###0##0#
#0000#00##0#
###0###0##0#
#000#0000#0#
#0#####0000#
#######0####

Output:
-1

-------------------

15 15
1 0
13 14
###############
0000#########0#
###0#####00##0#
#00000000#0##0#
#0######0####0#
#0######0#0##0#
#0000000000000#
##########0####
#0######000####
#0######000000#
#0##########00#
#0000000000000#
###0#######0###
#00000000000000
###############

Output:
28

RRRDDRRRRRDDDRRDDDRRDDLDDRRR

'''

"""**Part - 2**"""

'''
6 7
1 6
1 3
2 2
3 1
4 2
5 1
6 0
1 2
2 3
3 6
1 4
4 5
5 6
3 5

Output:
1

-------------------

6 7
1 6
1 6
2 4
3 2
4 5
5 2
6 0
1 2
2 3
3 6
1 4
4 5
5 6
3 5

Output:
0
1 2 3 4 5

-------------------

5 5
2 4
1 0
2 2
3 2
4 0
5 1
5 2
2 3
1 4
4 5
5 3

Output:
1

'''