# -*- coding: utf-8 -*-
"""23101137_Imtiaz Hossain_CSE422_30_Assignment02_Summer2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PS43mDb1-6yhTOtsr3LHBdIC_oFUdm6h
"""

# Task 1

import random
import math

class task1:
    grid_size = 25
    population_size = 6
    max_generations = 15
    mutation_rate = 0.9

    components = {'ALU': (5, 5), 'Cache': (7, 4), 'Control Unit': (4, 4),
                'Register File': (6, 6), 'Decoder': (5, 3), 'Floating Unit': (5, 5)}

    component_names = ['ALU', 'Cache', 'Control Unit', 'Register File', 'Decoder', 'Floating Unit']
    connections = [(3, 0), (2, 0), (0, 1), (3, 5), (1, 4), (4, 5)]

    #--> Overlap penalty
    alpha = 1000
    #--> Wire length penalty
    beta = 2
    #--> Bounding box area penalty
    gamma = 1

    def generate_random_chromosome(self):
        chromosome = []
        for i in self.component_names:
            width, height = self.components[i]

            x = random.randint(0, self.grid_size - width)
            y = random.randint(0, self.grid_size - height)

            chromosome.append((x, y))

        return chromosome

    def initialize_population(self):
        population = []
        i = 0
        while i < self.population_size:
            population.append(self.generate_random_chromosome())
            i += 1
        return population

    def overlap_count(self, chromosome):
        count = 0

        for i in range(len(chromosome)):
            for j in range(i + 1, len(chromosome)):

                name_i, name_j = self.component_names[i], self.component_names[j]

                width_i, height_i = self.components[name_i]
                width_j, height_j = self.components[name_j]

                x_i, y_i = chromosome[i]
                x_j, y_j = chromosome[j]

                a_right = x_i + width_i
                a_bottom = y_i
                a_left = x_i
                a_top = y_i + height_i

                b_left = x_j
                b_right = x_j + width_j
                b_bottom = y_j
                b_top = y_j + height_j

                if not (a_right <= b_left or b_right <= a_left or a_top <= b_bottom or b_top <= a_bottom):
                    count += 1

        return count


    def total_wire_length(self, chromosome):

        total = 0.0

        for i, j in self.connections: #--> 3, 0

            name_i = self.component_names[i]    #--> 'Register File'
            name_j = self.component_names[j]    #--> 'ALU'

            width_i, height_i = self.components[name_i]  #-->  (6, 6)
            width_j, height_j = self.components[name_j]  #-->  (5, 5)

            x_i, y_i = chromosome[i] #--> (1, 13)
            x_j, y_j = chromosome[j] #--> (9, 3)

            center_x_i, center_y_i = x_i + width_i / 2, y_i + height_i / 2
            center_x_j, center_y_j = x_j + width_j / 2, y_j + height_j / 2

            total += math.sqrt((center_x_i - center_x_j) ** 2 + (center_y_i - center_y_j) ** 2)

        return total

    def bounding_box_area(self, chromosome):
        min_x = float('inf')
        min_y = float('inf')

        max_x = float('-inf')
        max_y = float('-inf')

        for i in range(len(chromosome)):
            x, y = chromosome[i]
            width, height = self.components[self.component_names[i]]

            min_x = min(min_x, x)
            min_y = min(min_y, y)

            max_x = max(max_x, x + width)
            max_y = max(max_y, y + height)

        return (max_x - min_x) * (max_y - min_y)

    def calculate_fitness(self, chromosome):
        overlaps = self.overlap_count(chromosome)
        wire = self.total_wire_length(chromosome)
        area = self.bounding_box_area(chromosome)

        return -(self.alpha * overlaps + self.beta * wire + self.gamma * area)

    def random_selection(self, population, fitness_values):
        return random.choice(population)

    def tournament_selection(self, population, fitness_values, size=3):
        candidates = random.sample(list(zip(population, fitness_values)), size)
        return max(candidates, key=lambda x: x[1])[0]

    def single_point_crossover(self, parent1, parent2):
        point = random.randint(1, len(parent1) - 1)

        return parent1[:point] + parent2[point:], parent2[:point] + parent1[point:]

    # ===================== FOR TASK - 2 =======================

    def two_point_crossover(self, parent1, parent2):
        p1 = random.randint(1, len(parent1) - 2)
        p2 = random.randint(p1 + 1, len(parent1) - 1)

        return (parent1[:p1] + parent2[p1:p2] + parent1[p2:], parent2[:p1] + parent1[p1:p2] + parent2[p2:])

    #============================================================

    def mutate(self, chromosome):
        new_chrom = chromosome.copy()

        if random.random() < self.mutation_rate:
            idx = random.randint(0, len(new_chrom) - 1) #--> 0 → ALU, 1 → Cache...

            name = self.component_names[idx]

            w, h = self.components[name]

            x = random.randint(0, self.grid_size - w)
            y = random.randint(0, self.grid_size - h)

            new_chrom[idx] = (x, y)

        return new_chrom


    #--> Elitism selection --> Next generation population selection
    def next_generation_selection(self, population, fitness_values, offspring):

        combined_population = population + offspring
        offspring_fitness = []

        for child in offspring:
            fitness = self.calculate_fitness(child)
            offspring_fitness.append(fitness)

        combined_fitness = fitness_values + offspring_fitness

        paired = list(zip(combined_population, combined_fitness))
        sorted_paired = sorted(paired, key=lambda x: x[1], reverse=True)

        next_generation = []
        for i in range(self.population_size):
            chromosome, fitness = sorted_paired[i]
            next_generation.append(chromosome)

        return next_generation

    def genetic_algorithm(self, crossover_type='Single'):
        population = self.initialize_population()
        best_fitness_history = []
        best_fitness = float('-inf')
        best_chromosome = None
        last_improvement = 0

        for generation in range(self.max_generations):

            fitness_values = [self.calculate_fitness(ch) for ch in population]
            current_best = max(fitness_values)

            if current_best > best_fitness:
                best_fitness = current_best
                best_chromosome = population[fitness_values.index(current_best)]
                last_improvement = generation

            best_fitness_history.append(best_fitness)

            # ===== PLATEAU =====

            if (generation - last_improvement >= 5) and (generation >= 5):
                print()
                print(f"PLATEAU termination at generation {generation+1} - no improvement in 5 generations")
                break

            offspring = []

            for _ in range(self.population_size // 2):
                p1 = self.random_selection(population, fitness_values)
                p2 = self.random_selection(population, fitness_values)

                if crossover_type == 'Single':
                    c1, c2 = self.single_point_crossover(p1, p2)
                else:
                    c1, c2 = self.two_point_crossover(p1, p2)

                offspring.append(self.mutate(c1))
                offspring.append(self.mutate(c2))

            population = self.next_generation_selection(population, fitness_values, offspring)

        return {'best_chromosome': best_chromosome,'best_fitness': best_fitness, 'overlap_count': self.overlap_count(best_chromosome),
                'wire_length': self.total_wire_length(best_chromosome), 'bounding_area': self.bounding_box_area(best_chromosome),
                'fitness_history': best_fitness_history}

    def print_results(self, results):

        print("\n" + "---------------------------------------------------------")
        print("FINAL RESULTS")
        print("---------------------------------------------------------")
        print("Best fitness value:", round(results['best_fitness'], 2))
        print("Total overlap count:", results['overlap_count'])
        print("Total wire length:", round(results['wire_length'], 2))
        print("Total bounding box area:", results['bounding_area'])
        print("\nOptimal Component Placements (bottom-left coordinates):")
        print("---------------------------------------------------------")
        print()

        print(f"{'Component':<15} {'Position (x, y)':<20} {'Size (WxH)':<10}")
        print("-" * 45)

        for name, (x, y) in zip(self.component_names, results['best_chromosome']):
            w, h = self.components[name]
            print(f"{name:<15} ({x}, {y}){'':<15} {w}x{h}")


    def verify_sample_calculation(self):

        print("\n" + "---------------------------------------------------------")
        print("Just for checking sample calculation")
        print("---------------------------------------------------------")
        print()

        sample = [(9, 3), (12, 15), (13, 16), (1, 13), (4, 15), (9, 6)]
        for i, (x, y) in enumerate(sample):
            name = self.component_names[i]
            w, h = self.components[name]
            print(f"{name}: ({x}, {y}) - Size: {w}x{h}")
            print(f"            - Boundaries: x=[{x},{x+w}]")
            print(f"                          y=[{y},{y+h}]\n")

        overlaps = self.overlap_count(sample)
        wire = self.total_wire_length(sample)
        area = self.bounding_box_area(sample)
        fitness = self.calculate_fitness(sample)


        print("\nCalculated Result:")
        print("                     Overlap count:", overlaps)
        print("                     Wire length:", round(wire, 2))
        print("                     Bounding area:", area)
        print("                     Fitness:", round(fitness, 2))
        print()
        print("---------------------------------------------------------")



    def sample_population(self):
        return [[(9, 3), (12, 15), (13, 16), (1, 13), (4, 15), (9, 6)],
                [(8, 0), (7, 12), (4, 11), (1, 13), (14, 10), (9, 11)],
                [(6, 5), (12, 9), (9, 7), (8, 6), (2, 7), (3, 1)],
                [(3, 11), (11, 12), (14, 11), (6, 10), (3, 11), (3, 0)],
                [(10, 12), (8, 16), (10, 4), (13, 6), (6, 0), (3, 7)],
                [(0, 2), (0, 0), (14, 12), (4, 5), (12, 4), (3, 10)]]

    def genetic_algorithm_with_sample(self, crossover_type='Single'):
        population = self.sample_population()
        best_fitness_history = []
        best_fitness = float('-inf')
        best_chromosome = None
        last_improvement = 0

        print("Best Fitness for,\n")
        for generation in range(self.max_generations):

            fitness_values = []
            for i in population:
                fitness = self.calculate_fitness(i)
                fitness_values.append(fitness)

            current_best = max(fitness_values)

            if current_best > best_fitness:
                best_fitness = current_best
                best_chromosome = population[fitness_values.index(current_best)]
                last_improvement = generation

            best_fitness_history.append(best_fitness)

            # ===== PLATEAU =====

            if (generation - last_improvement >= 5) and (generation >= 5):
                print()
                print(f"PLATEAU termination at generation {generation+1} - no improvement in 5 generations")
                break

            print(f"Gen. {generation+1} = {round(best_fitness, 2)}")

            offspring = []
            for o in range(self.population_size // 2):
                p1 = self.random_selection(population, fitness_values)
                p2 = self.random_selection(population, fitness_values)

                if crossover_type == 'Single':
                    c1, c2 = self.single_point_crossover(p1, p2)
                else:
                    c1, c2 = self.two_point_crossover(p1, p2)

                offspring.append(self.mutate(c1))
                offspring.append(self.mutate(c2))

            population = self.next_generation_selection(population, fitness_values, offspring)

        return {'best_chromosome': best_chromosome, 'best_fitness': best_fitness, 'overlap_count': self.overlap_count(best_chromosome),
                'wire_length': self.total_wire_length(best_chromosome), 'bounding_area': self.bounding_box_area(best_chromosome),
                'fitness_history': best_fitness_history}


obj1 = task1()
obj1.verify_sample_calculation()  #--> Just for testing
print()
print("TASK 1: Single-Point Crossover")
print()
print("---------------------------------------------------------")
print()

single_point_result = obj1.genetic_algorithm_with_sample(crossover_type='Single')
obj1.print_results(single_point_result)

# TASK - 2

print("---------------------------------------------------------")
print()
print("TASK 2: Two-Point Crossover")
print()
print("---------------------------------------------------------")

two_point_result = obj1.genetic_algorithm_with_sample(crossover_type='Two')
obj1.print_results(two_point_result)
print("---------------------------------------------------------")